"""
sentinel/detection/catalog.py
=============================
Human-readable catalog of every detector (served by ``/api/v1/detection/detectors``).
"""

DETECTORS = [
    {"id": "D1.chsh_certificate", "name": "CHSH entanglement certificate", "layer": "entanglement", "conclusive": True,
     "statistic": "Lower confidence bound of S = E(A0,B0)+E(A0,B1)+E(A1,B0)−E(A1,B1)",
     "null_hypothesis": "The pairs admit a local (classical) model: S ≤ 2",
     "description": "Sacrificial Bell pairs must beat the classical bound before any key qubit is trusted.",
     "severity_rule": "CRITICAL when the bound does not exceed 2"},
    {"id": "D2.chsh_drift", "name": "CHSH drift", "layer": "entanglement", "conclusive": False,
     "statistic": "z = (S0 − S) / √(se² + se0²)", "null_hypothesis": "S equals the calibrated baseline",
     "description": "A significant fall of the Bell value against the link's measured baseline.",
     "severity_rule": "HIGH if ΔS ≥ 0.25, else MEDIUM; floor ΔS ≥ 0.10"},
    {"id": "D3a.witness_certificate", "name": "Fidelity witness certificate", "layer": "entanglement", "conclusive": True,
     "statistic": "Lower bound of F = (1 + ⟨XX⟩ − ⟨YY⟩ + ⟨ZZ⟩)/4", "null_hypothesis": "F ≤ 1/2 (separable)",
     "description": "A second, basis-aligned entanglement certificate.", "severity_rule": "CRITICAL when F_lcb ≤ 1/2"},
    {"id": "D3b.witness_drift", "name": "Witness drift", "layer": "entanglement", "conclusive": False,
     "statistic": "Per-basis disagreement fractions vs baseline (two-proportion)", "null_hypothesis": "No change",
     "description": "Which Pauli correlations degraded, and by how much.", "severity_rule": "HIGH if ΔF ≥ 0.05; floor 0.02"},
    {"id": "D4.qber_excess", "name": "QBER excess", "layer": "channel", "conclusive": False,
     "statistic": "Per-basis mismatch rate on parameter-estimation positions vs baseline", "null_hypothesis": "No rise",
     "description": "Errors on teleported key states in each Pauli basis.", "severity_rule": "HIGH ≥ 5 pts, MEDIUM ≥ 2 pts; floor 1 pt"},
    {"id": "D5.tomography_deviation", "name": "De-twirled channel tomography", "layer": "channel", "conclusive": False,
     "statistic": "χ² homogeneity over 18 de-twirled Bloch cells", "null_hypothesis": "Channel equals baseline",
     "description": "Reconstructs the full Bloch map by undoing teleportation's Pauli twirl, then names its shape.",
     "severity_rule": "HIGH if max|Δr| ≥ 0.1, else MEDIUM; floor 0.04"},
    {"id": "D6.frame_integrity", "name": "Classical frame integrity", "layer": "classical", "conclusive": True,
     "statistic": "Correction-bit mismatches on sampled positions (or Wegman–Carter MAC)",
     "null_hypothesis": "Classical channel unaltered", "description": "Tampering with teleportation's two classical bits.",
     "severity_rule": "CRITICAL on any mismatch"},
    {"id": "D7.bell_consistency", "name": "Source honesty", "layer": "source", "conclusive": False,
     "statistic": "Key QBER − Bell-predicted QBER (two-sided)", "null_hypothesis": "Key states travelled the certified channel",
     "description": "Excess exposes a signer sending states other than claimed; deficit exposes a relay/MITM.",
     "severity_rule": "HIGH; floor 1 pt"},
    {"id": "D8.copy_consistency", "name": "Recipient copy consistency", "layer": "source", "conclusive": False,
     "statistic": "QBER of the two recipients' copies (two-sided)", "null_hypothesis": "Copies equally good",
     "description": "A dishonest signer preparing a repudiation dispute corrupts one copy.", "severity_rule": "HIGH; floor 1 pt"},
    {"id": "D9.security_margin", "name": "Security margin", "layer": "security", "conclusive": True,
     "statistic": "Feasibility of s_a < s_v at the measured error bound", "null_hypothesis": "—",
     "description": "Whether thresholds meeting the security targets exist at all.", "severity_rule": "MEDIUM; aborts the bundle"},
    {"id": "D10.cusum", "name": "Temporal drift (CUSUM)", "layer": "temporal", "conclusive": False,
     "statistic": "Page's CUSUM of QBER and CHSH shifts, noise-aware limits", "null_hypothesis": "No persistent shift",
     "description": "Accumulates shifts too small for any single run.", "severity_rule": "MEDIUM on alarm"},
    {"id": "S1.authorization", "name": "Verifier authorization", "layer": "protocol", "conclusive": True,
     "statistic": "Recipient-set membership", "null_hypothesis": "—", "description": "Only recipients hold the quantum public key.",
     "severity_rule": "CRITICAL"},
    {"id": "S2.key_binding", "name": "Signer key binding", "layer": "protocol", "conclusive": True,
     "statistic": "Bundle owner vs claimed signer", "null_hypothesis": "—", "description": "A valid key is not the right key.",
     "severity_rule": "CRITICAL"},
    {"id": "S3.bundle_state", "name": "One-time bundle state", "layer": "protocol", "conclusive": True,
     "statistic": "Lifecycle status and per-recipient consumption", "null_hypothesis": "—",
     "description": "Each bundle verifies at most once per recipient.", "severity_rule": "CRITICAL"},
    {"id": "S4.nonce", "name": "Nonce freshness", "layer": "protocol", "conclusive": True, "statistic": "Nonce registry",
     "null_hypothesis": "—", "description": "Each nonce is accepted once.", "severity_rule": "CRITICAL"},
    {"id": "S5.sequence", "name": "Sequence monotonicity", "layer": "protocol", "conclusive": True,
     "statistic": "Signed sequence number vs last accepted", "null_hypothesis": "—", "description": "Rejects regressions.",
     "severity_rule": "CRITICAL"},
    {"id": "S6.freshness", "name": "Freshness window", "layer": "protocol", "conclusive": True,
     "statistic": "Signed timestamp age", "null_hypothesis": "—", "description": "Rejects delayed delivery.", "severity_rule": "CRITICAL"},
    {"id": "S7.key_tests", "name": "Key mismatch tests", "layer": "signature", "conclusive": False,
     "statistic": "Mismatches on tested positions per key and set vs designed threshold",
     "null_hypothesis": "Honest noise only", "description": "The quantum verification itself.", "severity_rule": "CRITICAL on any failed key"},
    {"id": "S8.sprt", "name": "Sequential early abort", "layer": "signature", "conclusive": False,
     "statistic": "Wald SPRT log-likelihood ratio", "null_hypothesis": "rate = honest bound",
     "description": "Rejects forgeries after reading a small fraction of the signature.", "severity_rule": "CRITICAL on early reject"},
    {"id": "S9.forensics", "name": "Forensic attribution", "layer": "signature", "conclusive": False,
     "statistic": "Failure fraction, failed-set mismatch rate, own/recv asymmetry", "null_hypothesis": "—",
     "description": "Names what the forger knew, and who, when the pattern allows.", "severity_rule": "HIGH"},
    {"id": "S10.transfer_consistency", "name": "Transferability", "layer": "signature", "conclusive": False,
     "statistic": "First-recipient vs transferee decision", "null_hypothesis": "—",
     "description": "A dispute is what a repudiating signer wants; symmetrization makes it rare.", "severity_rule": "HIGH"},
]
