/* Explain-drawer content: static educational text (no measured numbers). */
export interface Explanation { title: string; what: string; how: string; tex?: string; why: string; limits?: string; method?: string }

export const EXPLAIN: Record<string, Explanation> = {
  chsh: {
    title: 'CHSH Bell test', method: 'bell',
    what: 'A game played with sacrificial entangled pairs. Two parties measure in randomly chosen settings and correlate their ±1 outcomes.',
    how: 'We estimate four correlators E(a,b) from the counts and combine them. A Clopper–Pearson bound on each correlator gives a lower confidence bound S_lcb.',
    tex: 'S = E(A_0,B_0) + E(A_0,B_1) + E(A_1,B_0) - E(A_1,B_1),\\quad |S|_{\\text{local}} \\le 2 \\le 2\\sqrt2',
    why: 'Only genuine entanglement exceeds 2. If S_lcb ≤ 2 the link cannot be trusted to teleport key states, whatever else looks fine: an interceptor that measures the pairs destroys the violation.',
    limits: 'Finite statistics: S_lcb is conservative by design. A drop that keeps S_lcb above 2 is still caught by the drift test (D2) against the calibrated baseline.',
  },
  witness: {
    title: 'Fidelity witness', method: 'bell',
    what: 'A second entanglement certificate built from Pauli correlations measured on Bell pairs.',
    how: 'F is estimated from ⟨XX⟩, ⟨YY⟩ and ⟨ZZ⟩ with a lower confidence bound.',
    tex: 'F = \\tfrac14\\,(1 + \\langle XX\\rangle - \\langle YY\\rangle + \\langle ZZ\\rangle) > \\tfrac12 \\Rightarrow \\text{entangled}',
    why: 'Basis-resolved: it shows which correlation an adversary disturbed.',
  },
  qber: {
    title: 'Quantum bit error rate', method: 'detection',
    what: 'The fraction of parameter-estimation positions where the verifier’s outcome disagrees with the signer’s revealed state, measured in the matching basis.',
    how: 'Per-basis counts on the sacrificed PE positions, compared with the link’s calibrated baseline by a two-proportion test (Fisher exact for small counts).',
    why: 'Every tampering strategy that touches the qubits raises errors in at least one basis. QBER also sets the honest error bound e_ucb that the signature thresholds are designed around.',
  },
  detwirl: {
    title: 'Pauli-frame de-twirled tomography', method: 'tomography',
    what: 'Reconstruction of the full Bloch map (M, c) of the quantum channel, even though teleportation “twirls” it.',
    how: 'Teleportation applies a random Pauli frame k then the correction c. Averaged over k the channel looks depolarizing, which hides damping and rotations. Because the signer knows k and the verifier knows c, each PE outcome is an unbiased sample of the channel at a known input, so the frame can be undone.',
    tex: '\\mathcal N(r_{\\pi_k(\\ell)}) = P_c\\, r_{\\text{fin}}',
    why: 'It turns “errors went up” into a fingerprint: dephasing, amplitude damping, coherent rotation, intercept-resend or a classical frame attack each deform the ellipsoid differently.',
    limits: 'Some channels are physically indistinguishable; the classifier lists them as alternatives instead of guessing.',
  },
  frame: {
    title: 'Classical frame integrity', method: 'detection',
    what: 'Teleportation needs two classical bits per qubit. Flipping them corrupts the state without touching the fibre.',
    how: 'On sampled positions the signer’s Bell outcome k is compared with the correction c the verifier applied (or a Wegman–Carter MAC authenticates them).',
    why: 'A classical-channel attacker is invisible to Bell tests; this check catches any flip conclusively.',
  },
  source_consistency: {
    title: 'Source honesty (D7)', method: 'detection',
    what: 'Key QBER compared with the QBER that the certified Bell pairs predict.',
    how: 'Two-sided test on key-state errors vs Bell-predicted errors per basis.',
    why: 'Excess errors mean the signer sent states other than claimed (repudiation preparation); a deficit exposes a relay that replaced the channel.',
  },
  copy_consistency: {
    title: 'Recipient copy consistency (D8)', method: 'detection',
    what: 'The two recipients’ copies of the quantum public key should be equally good.',
    how: 'Two-proportion test between the recipients’ QBERs.',
    why: 'A signer preparing a dispute corrupts one copy so one verifier accepts and the other rejects.',
  },
  margin: {
    title: 'Security margin (D9)', method: 'bounds',
    what: 'Whether thresholds s_a < s_v that meet the security targets exist at the measured error bound.',
    how: 'The designer maximises over the tested-position count n with exact binomial tails.',
    why: 'If the channel is too noisy, no threshold is safe: the bundle is refused instead of silently weakening security.',
  },
  cusum: {
    title: 'CUSUM drift monitor (D10)', method: 'detection',
    what: 'Page’s cumulative sum of small QBER rises and CHSH drops across bundles.',
    how: 'C_t = max(0, C_{t−1} + x_t − k); alarm when C_t > h. k and h are noise-aware (k ≥ 2σ, h ≥ 6σ). Runs already flagged by single-run detectors are excluded.',
    tex: 'C_t = \\max(0,\\, C_{t-1} + (x_t - x_0) - k),\\quad C_t > h \\Rightarrow \\text{alarm}',
    why: 'A low-and-slow attacker stays under every single-run test; the accumulator catches the persistence.',
  },
  key_tests: {
    title: 'Key mismatch tests (S7)', method: 'protocol',
    what: 'The quantum verification itself. For each digest bit the signer reveals one of two one-time keys; the verifier checks the revealed labels against its measured records.',
    how: 'On positions measured in the revealed basis, count mismatches m out of n and accept the key if m ≤ s·n (s_a for the first recipient, s_v after transfer).',
    tex: '\\text{accept key} \\iff m \\le s_a\\, n,\\qquad n \\ge n_{\\min}',
    why: 'A forger who never saw the key’s states must guess them: at least 1/3 mismatches in expectation, far above the honest rate.',
  },
  sprt: {
    title: 'Sequential early abort (S8)', method: 'protocol',
    what: 'Wald’s sequential probability ratio test on the mismatch stream.',
    how: 'The log-likelihood ratio of “forger rate 1/3” vs “honest bound e” is accumulated; crossing A rejects early.',
    tex: '\\Lambda_n = \\sum_i \\log \\frac{p_1^{x_i}(1-p_1)^{1-x_i}}{p_0^{x_i}(1-p_0)^{1-x_i}}',
    why: 'Forgeries are rejected after reading a small fraction of the signature.',
  },
  forensics: {
    title: 'Forensic attribution (S9)', method: 'detection',
    what: 'After a rejection, the pattern of failures names what the forger knew.',
    how: 'Failure fraction, failed-set mismatch rate (≈1/2 external, ≈1/3 insider) and own/received-set asymmetry.',
    why: 'An insider can forge the half of the records it forwarded, never the half the other verifier kept: that asymmetry names the insider.',
  },
  protocol_guard: {
    title: 'Protocol guard (S1–S6)', method: 'protocol',
    what: 'Conclusive classical checks: authorization, key binding, one-time bundle state, nonce, sequence number, freshness window.',
    how: 'Registry lookups against state stored by the verifier.',
    why: 'Replay and impersonation can be physically invisible (the quantum statistics are perfect); the protocol layer catches them.',
  },
  symmetrization: {
    title: 'Symmetrization', method: 'protocol',
    what: 'Each recipient forwards a random half of its measurement records to the other over an authenticated channel.',
    how: 'Both verifiers then test the signature against a mixture of own and received records.',
    why: 'A dishonest signer cannot make one recipient accept and the other reject (repudiation), because neither knows which records the other holds.',
  },
  thresholds: {
    title: 'Threshold designer', method: 'bounds',
    what: 'Chooses s_a < s_v from exact binomial tails so all three security targets hold.',
    how: 'ε_rob from the honest tail above s_a, ε_forge from the forger tail below s_v at p = 1/3, ε_rep from the hypergeometric split between them.',
    why: 'Security is stated as a number, not as a claim.',
  },
  eps_rob: { title: 'ε_rob — robustness', method: 'bounds', what: 'Probability that an honest signature is rejected.', how: 'Union bound of per-key honest binomial tails beyond s_a plus the PE and SPRT budgets.', why: 'Keeps false rejections provably rare.' },
  eps_forge: { title: 'ε_forge — forgery', method: 'bounds', what: 'Probability that a forger’s key passes the transferee threshold s_v.', how: 'Binomial CDF at p_forge = 1/3 (insider optimum over all measurement strategies).', why: 'The unforgeability guarantee.' },
  eps_rep: { title: 'ε_rep — repudiation', method: 'bounds', what: 'Probability that a signer makes the recipients disagree.', how: 'Hypergeometric tail of the symmetrized split between s_a and s_v.', why: 'The non-repudiation guarantee.' },
  holm: { title: 'Holm–Bonferroni', method: 'detection', what: 'Family-wise error control across all statistical detectors in one run.', how: 'Sorted p-values against α/(m−i+1), with effect-size floors.', why: 'Many detectors must not multiply false alarms.' },
  teleportation: { title: 'Teleportation', method: 'protocol', what: 'Moves a qubit state using a Bell pair plus two classical bits.', how: 'Bell measurement gives k; the receiver applies the Pauli correction c (X^{m1} Z^{m0}).', tex: '|\\psi\\rangle|\\Phi^+\\rangle \\to \\tfrac12\\sum_k |\\beta_k\\rangle\\, \\sigma_k|\\psi\\rangle', why: 'The key state that gets verified is the one that came out of the certified channel.' },
  six_state: { title: 'Six-state encoding', method: 'protocol', what: 'Key positions are uniformly random eigenstates of X, Y or Z.', how: 'Labels from the CSPRNG; the verifier measures in a random basis.', why: 'Maximises the error any measurement-based attack must cause (1/3 for the optimal insider).' },
  lamport: { title: 'Lamport one-time keys', method: 'protocol', what: 'Two keys per digest bit; signing reveals one of each pair.', how: 'The digest bits select the revealed keys.', why: 'A bundle signs exactly one message; reuse is refused (S3).' },
  ledger: { title: 'Audit ledger', method: 'ledger', what: 'An append-only, hash-chained log of every session, incident and action.', how: 'Each block commits to the previous hash and a Merkle root of its transactions.', why: 'Any edit to a stored record breaks the chain from that block on.' },
  merkle: { title: 'Merkle tree', method: 'ledger', what: 'A binary hash tree over the block’s transactions.', how: 'Leaves are SHA-256 of canonical JSON; parents hash their children.', why: 'An inclusion proof of log₂ n hashes shows a transaction is in a block.' },
  clopper_pearson: { title: 'Clopper–Pearson interval', method: 'bounds', what: 'Exact binomial confidence interval.', how: 'Beta-distribution quantiles.', why: 'No normal approximation: conservative at small counts and rates near 0.' },
  threat_score: { title: 'Threat score', method: 'detection', what: 'A UI-only summary of how strongly detectors fired.', how: '1 − Π(1 − w_sev · strength) over fired findings.', why: 'Decisions never use it; verdicts come from the decision list.' },
};
